package pluginManage

//add new file

var registerOp = map[string]int{
	//evm opcodes
	"STOP":           0,
	"ADD":            0,
	"MUL":            0,
	"SUB":            0,
	"DIV":            0,
	"SDIV":           0,
	"MOD":            0,
	"SMOD":           0,
	"EXP":            0,
	"NOT":            0,
	"LT":             0,
	"GT":             0,
	"SLT":            0,
	"SGT":            0,
	"EQ":             0,
	"ISZERO":         0,
	"SIGNEXTEND":     0,
	"AND":            0,
	"OR":             0,
	"XOR":            0,
	"BYTE":           0,
	"SHL":            0,
	"SHR":            0,
	"SAR":            0,
	"ADDMOD":         0,
	"MULMOD":         0,
	"SHA3":           0,
	"ADDRESS":        0,
	"BALANCE":        0,
	"ORIGIN":         0,
	"CALLER":         0,
	"CALLVALUE":      0,
	"CALLDATALOAD":   0,
	"CALLDATASIZE":   0,
	"CALLDATACOPY":   0,
	"DELEGATECALL":   0,
	"STATICCALL":     0,
	"CODESIZE":       0,
	"CODECOPY":       0,
	"GASPRICE":       0,
	"EXTCODESIZE":    0,
	"EXTCODECOPY":    0,
	"RETURNDATASIZE": 0,
	"RETURNDATACOPY": 0,
	"EXTCODEHASH":    0,
	"BLOCKHASH":      0,
	"COINBASE":       0,
	"TIMESTAMP":      0,
	"NUMBER":         0,
	"DIFFICULTY":     0,
	"GASLIMIT":       0,
	"POP":            0,
	"MLOAD":          0,
	"MSTORE":         0,
	"MSTORE8":        0,
	"SLOAD":          0,
	"SSTORE":         0,
	"JUMP":           0,
	"JUMPI":          0,
	"PC":             0,
	"MSIZE":          0,
	"GAS":            0,
	"JUMPDEST":       0,
	"PUSH1":          0,
	"PUSH2":          0,
	"PUSH3":          0,
	"PUSH4":          0,
	"PUSH5":          0,
	"PUSH6":          0,
	"PUSH7":          0,
	"PUSH8":          0,
	"PUSH9":          0,
	"PUSH10":         0,
	"PUSH11":         0,
	"PUSH12":         0,
	"PUSH13":         0,
	"PUSH14":         0,
	"PUSH15":         0,
	"PUSH16":         0,
	"PUSH17":         0,
	"PUSH18":         0,
	"PUSH19":         0,
	"PUSH20":         0,
	"PUSH21":         0,
	"PUSH22":         0,
	"PUSH23":         0,
	"PUSH24":         0,
	"PUSH25":         0,
	"PUSH26":         0,
	"PUSH27":         0,
	"PUSH28":         0,
	"PUSH29":         0,
	"PUSH30":         0,
	"PUSH31":         0,
	"PUSH32":         0,
	"DUP1":           0,
	"DUP2":           0,
	"DUP3":           0,
	"DUP4":           0,
	"DUP5":           0,
	"DUP6":           0,
	"DUP7":           0,
	"DUP8":           0,
	"DUP9":           0,
	"DUP10":          0,
	"DUP11":          0,
	"DUP12":          0,
	"DUP13":          0,
	"DUP14":          0,
	"DUP15":          0,
	"DUP16":          0,
	"SWAP1":          0,
	"SWAP2":          0,
	"SWAP3":          0,
	"SWAP4":          0,
	"SWAP5":          0,
	"SWAP6":          0,
	"SWAP7":          0,
	"SWAP8":          0,
	"SWAP9":          0,
	"SWAP10":         0,
	"SWAP11":         0,
	"SWAP12":         0,
	"SWAP13":         0,
	"SWAP14":         0,
	"SWAP15":         0,
	"SWAP16":         0,
	"LOG0":           0,
	"LOG1":           0,
	"LOG2":           0,
	"LOG3":           0,
	"LOG4":           0,
	"CREATE":         0,
	"CREATE2":        0,
	"CALL":           0,
	"RETURN":         0,
	"CALLCODE":       0,
	"REVERT":         0,
	"SELFDESTRUCT":   0,

	//add plugin
	"EXTERNALINFOSTART":	0,
	"EXTERNALINFOEND":		0,
	"CREATESTART":			0,
	"CREATEEND":			0,
	"CREATE2START":			0,
	"CREATE2END":			0,
	"CALLSTART":			0,
	"CALLEND":				0,
	"CALLCODESTART":		0,
	"CALLCODEEND":			0,
	"DELEGATECALLSTART":	0,
	"DELEGATECALLEND":		0,
	"STATICCALLSTART":		0,
	"STATICCALLEND":		0,
	"ENDSIGNAL":			0,
	"BLOCK_INFO":			0,
	"TXSTART":				0,
	"TXEND":				0,
	"TRANS_CREATE":			0,
	"TRANS_CREATE2":		0,
	"TRANS_CALL":			0,
	"TRANS_CALLCODE":		0,
	"TRANS_DELEGATECALL":	0,
	"TRANS_STATICCALL":		0,
	"TRANS_SUICIDE":		0,
}

var registerIALOp = map[string][]string {
	"IAL_BYTECODE":			[]string{"EXTERNALINFOEND","EXTERNALINFOEND","TRANS_CREATE","TRANS_CREATE2"},
	"IAL_INVOKE":			[]string{"EXTERNALINFOSTART","EXTERNALINFOEND","TRANS_CALL","TRANS_CALLCODE","TRANS_DELEGATECALL","TRANS_STATICCALL"},
	"IAL_MEMORY":			[]string{"SHA3","CALLDATACOPY","CODECOPY","RETURNDATACOPY","MLAOD","MSTORE","MSTORE8","CREATESTART","CREATEEND","CREATE2START","CREATE2END","CALLSTART","CALLEND","CALLCODESTART","CALLCODEEND","DELEGATECALLSTART","DELEGATECALLEND","STATICCALLSTART","STATICCALLEND","RETURN"},
	"IAL_STORAGE":			[]string{"SLOAD","SSTORE"},
	"IAL_ETH":				[]string{"TRANS_CREATE","TRANS_CALL","TRANS_CALLCODE","TRANS_SUICIDE"},
	"IAL_BALANCE":			[]string{"EXTERNALINFOSTART","EXTERNALINFOEND","CALLSTART","CALLEND","CALLCODESTART","CALLCODEEND","CREATESTART","CREATEEND","CREATE2START","CREATE2END","SELFDESTRUCT"},
	"IAL_CONTROLFLOW":		[]string{"JUMP","JUMPI"},
	"IAL_COMPARISON":		[]string{"LT","GT","SLT","SGT","NOT","EQ","ISZERO"},
	"IAL_ARITHMETIC":		[]string{"ADD","MUL","SUB","DIV","SDIV","MOD","SMOD","ADDMOD","MULMOD","EXP"},
	"IAL_EVENT":			[]string{"LOG0","LOG1","LOG2","LOG3","LOG4"},
}

func IsOpExist(opcode string) int {
	if _, opok := registerOp[opcode];opok{
		return 1
	}
	if _, IALok := registerIALOp[opcode];IALok{
		return 2
	}
	return 0
}

func ReturnIALArray(opcode string) []string {
	return registerIALOp[opcode]
}

func RetunOpcodeMap() map[string]int {
	return registerOp
}